// Tests the Supabase contract staleness guard.
//
// This test runs the `check_supabase_contracts.dart` script as a subprocess
// to verify its behavior under different conditions. It requires a clean git
// worktree to run correctly and cleans up any temporary files it creates.
import 'dart:io';
import 'package:flutter_test/flutter_test.dart';

void main() {
  const scriptPath = 'tool/check_supabase_contracts.dart';
  const artifactPath = 'supabase/types/database.ts';
  const tempMigrationPath = 'supabase/migrations/99999999_temp.sql';

  /// Writes a minimal-but-plausible typegen artifact so the guard's stub
  /// rejection (content checks) doesn't fire in tests that aren't about it.
  void writeValidArtifact(File file) {
    file.createSync(recursive: true);
    // ~2.2 KB so it also clears the minimum-size gate.
    final filler = '// filler line for size requirement\n' * 30;
    file.writeAsStringSync(
      'export type Database = {\n'
      '  __InternalSupabase: {\n'
      '    PostgrestVersion: "14.15"\n'
      '  }\n'
      '$filler}\n',
    );
  }

  group('check_supabase_contracts guard', () {
    test('fails when contract artifact does not exist', () {
      final artifact = File(artifactPath);
      final backup = File('$artifactPath.bak');
      if (artifact.existsSync()) {
        artifact.copySync(backup.path);
        artifact.deleteSync();
      }

      try {
        final result = Process.runSync('dart', [
          'run',
          scriptPath,
        ], runInShell: true);
        expect(result.exitCode, 1);
        expect(result.stdout.toString(), contains('[ERROR]'));
      } finally {
        if (backup.existsSync()) {
          backup.copySync(artifactPath);
          backup.deleteSync();
        }
      }
    });

    test(
      'fails when artifact is a hand-written stub without typegen markers',
      () {
        final artifact = File(artifactPath);
        final backup = File('$artifactPath.bak');
        if (artifact.existsSync()) {
          artifact.copySync(backup.path);
        }
        artifact.createSync(recursive: true);
        artifact.writeAsStringSync(
          '// Generated by Supabase CLI\n'
          'class AttendanceRecords {}\n',
        );

        try {
          final result = Process.runSync('dart', [
            'run',
            scriptPath,
          ], runInShell: true);
          expect(result.exitCode, 1);
          expect(result.stdout.toString(), contains('does not look like'));
        } finally {
          if (backup.existsSync()) {
            backup.copySync(artifactPath);
            backup.deleteSync();
          } else {
            artifact.deleteSync();
          }
        }
      },
    );

    test(
      'fails when uncommitted migration is staged but artifact not updated',
      () {
        final artifact = File(artifactPath);
        final tempMigration = File(tempMigrationPath);

        try {
          // Setup: ensure a valid artifact exists and is committed/clean in git.
          if (!artifact.existsSync()) {
            writeValidArtifact(artifact);
          } else {
            Process.runSync('git', ['restore', artifactPath], runInShell: true);
          }

          tempMigration.createSync(recursive: true);
          tempMigration.writeAsStringSync('-- temp migration\n');

          Process.runSync('git', ['add', tempMigrationPath], runInShell: true);

          // Execute guard
          final result = Process.runSync('dart', [
            'run',
            scriptPath,
          ], runInShell: true);

          // Assert
          expect(result.exitCode, 1);
          expect(result.stdout.toString(), contains('[ERROR]'));
        } finally {
          // Cleanup
          Process.runSync('git', [
            'restore',
            '--staged',
            tempMigrationPath,
          ], runInShell: true);
          if (tempMigration.existsSync()) {
            tempMigration.deleteSync();
          }
          Process.runSync('git', ['restore', artifactPath], runInShell: true);
        }
      },
    );

    test('passes when artifact exists and no migration change is made', () {
      final artifact = File(artifactPath);

      try {
        // Setup: ensure valid artifact exists
        if (!artifact.existsSync()) {
          writeValidArtifact(artifact);
        } else {
          Process.runSync('git', ['restore', artifactPath], runInShell: true);
        }

        // Execute guard
        final result = Process.runSync('dart', [
          'run',
          scriptPath,
        ], runInShell: true);

        // Assert
        expect(result.exitCode, 0);
        expect(
          result.stdout.toString(),
          contains('[OK] Contract verification passed.'),
        );
      } finally {
        Process.runSync('git', ['restore', artifactPath], runInShell: true);
      }
    });
  });
}
